### ISSUE TITLE
Typing parentheses opens the code completion popup

### ISSUE THREAD

**Issue by jonashungershausen** [vogellacompany/eclipse-dart#7]
![peek 2019-01-15 15-54](https://user-images.githubusercontent.com/5540255/51188247-dd3b4980-18dd-11e9-8bc7-85c5d76b82b9.gif)

**Comment by DanTup** [comment]
This might be the servers fault - the trigger characters may need some work:

https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/lsp/handlers/handler_initialize.dart#L66

I'll make a note to try and take a look at this next week.

**Comment by DanTup** [comment]
I've raised a change to remove the commit characters that I think may trigger in bad places:

https://dart-review.googlesource.com/c/sdk/+/90401

This is based on [the logic in the Dart VS Code plugin](https://github.com/Dart-Code/Dart-Code/blob/68d1cd271e88a785570257d487adbdec17abd6a3/src/providers/dart_completion_item_provider.ts#L36-L64). I will re-enable each of these characters when I'm able to do it based on the context (eg. so `{` will trigger it only if typed immediately after a `$` in a string).

Assuming the change lands today, it'll be in the next nightly SDK (tomorrow).

**Comment by DanTup** [comment]
I landed the change that removed it today (https://github.com/dart-lang/sdk/commit/9e0e1759672cb80b3a1d1654b173f62cd83fa952) so it'll be in tomorrows nightly. I'll ping you when the trigger characters are re-added with context (it might not be immediately though).

Let me know if you spot any other weird issues like this!

**Comment by jonashungershausen** [comment]
Works with the latest nightly build. Thanks @DanTup!
